language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
branches:
  except:
  only:
  - /.*/

install:
  - pip install coverage
  - pip install coveralls
script:
  - coverage run -m unittest discover
after_success:
  - coveralls
